// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DownloadFilePathsPostResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The etag property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Etag { get; set; }
#nullable restore
#else
        public string Etag { get; set; }
#endif
        /// <summary>The files property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePathsPostResponse_files>? Files { get; set; }
#nullable restore
#else
        public List<global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePathsPostResponse_files> Files { get; set; }
#endif
        /// <summary>The generatedAt property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GeneratedAt { get; set; }
#nullable restore
#else
        public string GeneratedAt { get; set; }
#endif
        /// <summary>The version property</summary>
        public double? Version { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePathsPostResponse"/> and sets the default values.
        /// </summary>
        public DownloadFilePathsPostResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePathsPostResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePathsPostResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePathsPostResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "etag", n => { Etag = n.GetStringValue(); } },
                { "files", n => { Files = n.GetCollectionOfObjectValues<global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePathsPostResponse_files>(global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePathsPostResponse_files.CreateFromDiscriminatorValue)?.AsList(); } },
                { "generatedAt", n => { GeneratedAt = n.GetStringValue(); } },
                { "version", n => { Version = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("etag", Etag);
            writer.WriteCollectionOfObjectValues<global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePathsPostResponse_files>("files", Files);
            writer.WriteStringValue("generatedAt", GeneratedAt);
            writer.WriteDoubleValue("version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
