// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths
{
    /// <summary>
    /// Builds and executes requests for operations under \download-file-paths
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DownloadFilePathsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePathsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DownloadFilePathsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/download-file-paths", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePathsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DownloadFilePathsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/download-file-paths", rawUrl)
        {
        }
        /// <summary>
        /// 指定したリポジトリから複数ファイルの RAW URL を生成し、JSON で返却するエンドポイントです。用途: UI からの一括ダウンロードや外部連携。リクエスト:- JSON Body { paths: string[] } を必須とし、空文字・重複・不正パスを検証します。制限:- 件数上限: 300。- 単一ファイル上限: 104857600 bytes。合計上限: 1073741824 bytes。レート制限:- Token Bucket を使用します。X-RateLimit-* ヘッダを返却し、超過時は 429 を返します。キャッシュ:- If-None-Match を評価し、ETag が一致する場合は 304 を返します。エラー応答:- application/problem+json を返します。type は validation / unprocessable / rate-limit / internal を使用します。
        /// </summary>
        /// <returns>A <see cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePathsPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePaths400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePaths422Error">When receiving a 422 status code</exception>
        /// <exception cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePaths429Error">When receiving a 429 status code</exception>
        /// <exception cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePaths500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePathsPostResponse?> PostAsDownloadFilePathsPostResponseAsync(global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePathsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePathsPostResponse> PostAsDownloadFilePathsPostResponseAsync(global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePathsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePaths400Error.CreateFromDiscriminatorValue },
                { "422", global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePaths422Error.CreateFromDiscriminatorValue },
                { "429", global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePaths429Error.CreateFromDiscriminatorValue },
                { "500", global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePaths500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePathsPostResponse>(requestInfo, global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePathsPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 指定したリポジトリから複数ファイルの RAW URL を生成し、JSON で返却するエンドポイントです。用途: UI からの一括ダウンロードや外部連携。リクエスト:- JSON Body { paths: string[] } を必須とし、空文字・重複・不正パスを検証します。制限:- 件数上限: 300。- 単一ファイル上限: 104857600 bytes。合計上限: 1073741824 bytes。レート制限:- Token Bucket を使用します。X-RateLimit-* ヘッダを返却し、超過時は 429 を返します。キャッシュ:- If-None-Match を評価し、ETag が一致する場合は 304 を返します。エラー応答:- application/problem+json を返します。type は validation / unprocessable / rate-limit / internal を使用します。
        /// </summary>
        /// <returns>A <see cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePathsResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePaths400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePaths422Error">When receiving a 422 status code</exception>
        /// <exception cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePaths429Error">When receiving a 429 status code</exception>
        /// <exception cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePaths500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use PostAsDownloadFilePathsPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePathsResponse?> PostAsync(global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePathsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePathsResponse> PostAsync(global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePathsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePaths400Error.CreateFromDiscriminatorValue },
                { "422", global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePaths422Error.CreateFromDiscriminatorValue },
                { "429", global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePaths429Error.CreateFromDiscriminatorValue },
                { "500", global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePaths500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePathsResponse>(requestInfo, global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePathsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 指定したリポジトリから複数ファイルの RAW URL を生成し、JSON で返却するエンドポイントです。用途: UI からの一括ダウンロードや外部連携。リクエスト:- JSON Body { paths: string[] } を必須とし、空文字・重複・不正パスを検証します。制限:- 件数上限: 300。- 単一ファイル上限: 104857600 bytes。合計上限: 1073741824 bytes。レート制限:- Token Bucket を使用します。X-RateLimit-* ヘッダを返却し、超過時は 429 を返します。キャッシュ:- If-None-Match を評価し、ETag が一致する場合は 304 を返します。エラー応答:- application/problem+json を返します。type は validation / unprocessable / rate-limit / internal を使用します。
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePathsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePathsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePathsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePathsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePathsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DownloadFilePathsRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
