//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DcsTranslationTool.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DcsTranslationTool.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   DCS Translation Tool に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認事項 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreatePullRequestDialogConfirmationLabel {
            get {
                return ResourceManager.GetString("CreatePullRequestDialogConfirmationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップロード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreatePullRequestDialogCreatePRButtonContent {
            get {
                return ResourceManager.GetString("CreatePullRequestDialogCreatePRButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除するファイルリスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreatePullRequestDialogDeleteFileListHeader {
            get {
                return ResourceManager.GetString("CreatePullRequestDialogDeleteFileListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   主な変更点 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreatePullRequestDialogMainChangesLabel {
            get {
                return ResourceManager.GetString("CreatePullRequestDialogMainChangesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PRタイトル： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreatePullRequestDialogPRTitleLabel {
            get {
                return ResourceManager.GetString("CreatePullRequestDialogPRTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;!-- 具体的な変更内容を記載してください --&gt;
        ///- mizファイル単位で箇条書きで記載してください
        ///- 機体やキャンペーン全体に関連する場合、機体やキャンペーンごとの記載でも大丈夫です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreatePullRequestDialogPullRequestDetailPlaceholder {
            get {
                return ResourceManager.GetString("CreatePullRequestDialogPullRequestDetailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変更内容 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreatePullRequestDialogPullRequestDetailTitle {
            get {
                return ResourceManager.GetString("CreatePullRequestDialogPullRequestDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;!-- このPRを使用するうえで注意すべきことをリストアップしてください --&gt;
        ///&lt;!-- 必要がなければ N/A としてください --&gt;
        ///N/A に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreatePullRequestDialogPullRequestNotePlaceholder {
            get {
                return ResourceManager.GetString("CreatePullRequestDialogPullRequestNotePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   留意点 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreatePullRequestDialogPullRequestNoteTitle {
            get {
                return ResourceManager.GetString("CreatePullRequestDialogPullRequestNoteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この変更の目的・背景を簡潔に書いてください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreatePullRequestDialogPullRequestSummaryPlaceholder {
            get {
                return ResourceManager.GetString("CreatePullRequestDialogPullRequestSummaryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   概要 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreatePullRequestDialogPullRequestSummaryTitle {
            get {
                return ResourceManager.GetString("CreatePullRequestDialogPullRequestSummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ## 📌 概要
        ///
        ///&lt;!-- このPRの目的・背景を簡潔に書いてください --&gt;
        ///
        ///## 🛠 変更内容
        ///
        ///&lt;!-- 具体的な変更内容を記載してください --&gt;
        ///- mizファイル単位で箇条書きで記載してください
        ///- 機体やキャンペーン全体に関連する場合、機体やキャンペーンごとの記載でも大丈夫です
        ///
        ///## ⚠️ 留意点
        ///
        ///&lt;!-- このPRを使用するうえで注意すべきことをリストアップしてください --&gt;
        ///&lt;!-- 必要がなければ N/A としてください --&gt;
        ///N/A
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreatePullRequestDialogPullRequestTemplate {
            get {
                return ResourceManager.GetString("CreatePullRequestDialogPullRequestTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップロードするファイルリスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreatePullRequestDialogUploadFileListHeader {
            get {
                return ResourceManager.GetString("CreatePullRequestDialogUploadFileListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   適用 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DownloadPageApplyButtonContent {
            get {
                return ResourceManager.GetString("DownloadPageApplyButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DownloadPageDownloadButtonContent {
            get {
                return ResourceManager.GetString("DownloadPageDownloadButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DownloadPageFetchButtonContent {
            get {
                return ResourceManager.GetString("DownloadPageFetchButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DownloadPageFilterAllContentText {
            get {
                return ResourceManager.GetString("DownloadPageFilterAllContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DownloadPageFilterLocalOnlyText {
            get {
                return ResourceManager.GetString("DownloadPageFilterLocalOnlyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変更/更新 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DownloadPageFilterModifiedText {
            get {
                return ResourceManager.GetString("DownloadPageFilterModifiedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未DL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DownloadPageFilterRepoOnlyText {
            get {
                return ResourceManager.GetString("DownloadPageFilterRepoOnlyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DL済 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DownloadPageFilterUnchangedText {
            get {
                return ResourceManager.GetString("DownloadPageFilterUnchangedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォルダ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DownloadPageOpenDirectoryButtonContent {
            get {
                return ResourceManager.GetString("DownloadPageOpenDirectoryButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DownloadPageTitle {
            get {
                return ResourceManager.GetString("DownloadPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Main に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DCS:World の日本語化をサポートする非公式ツールです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageAboutText {
            get {
                return ResourceManager.GetString("SettingsPageAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このアプリケーションについて に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageAboutTitle {
            get {
                return ResourceManager.GetString("SettingsPageAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テーマ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageChooseThemeText {
            get {
                return ResourceManager.GetString("SettingsPageChooseThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォルダー設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageDirectorySettingsTitle {
            get {
                return ResourceManager.GetString("SettingsPageDirectorySettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ライセンス情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageLicensesTitle {
            get {
                return ResourceManager.GetString("SettingsPageLicensesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   個人用設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPagePersonalizationTitle {
            get {
                return ResourceManager.GetString("SettingsPagePersonalizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プライバシーポリシー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPagePrivacyPolicyText {
            get {
                return ResourceManager.GetString("SettingsPagePrivacyPolicyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dark に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageRadioButtonDarkTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageRadioButtonLightTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageRadioButtonWindowsDefaultTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonWindowsDefaultTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最新版を探す に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageReleaseLatestText {
            get {
                return ResourceManager.GetString("SettingsPageReleaseLatestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   参照 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageSelectButton {
            get {
                return ResourceManager.GetString("SettingsPageSelectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   翻訳ファイルをmizファイルに適用する機体フォルダーのパス。
        ///&lt;DCSWorldインストールディレクトリ&gt;/Mods/aircraft と同じフォルダー構成にしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageSourceAircraftDirExplanationText {
            get {
                return ResourceManager.GetString("SettingsPageSourceAircraftDirExplanationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aircraft フォルダー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageSourceAircraftDirText {
            get {
                return ResourceManager.GetString("SettingsPageSourceAircraftDirText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   翻訳ファイルをmizファイルに適用するDLCキャンペーンフォルダーのパス。
        ///&lt;DCSWorldインストールディレクトリ&gt;/Mods/campaigns と同じフォルダー構成にしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageSourceDlcCampaignDirExplanationText {
            get {
                return ResourceManager.GetString("SettingsPageSourceDlcCampaignDirExplanationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Campaigns フォルダー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageSourceDlcCampaignDirText {
            get {
                return ResourceManager.GetString("SettingsPageSourceDlcCampaignDirText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ダウンロードした翻訳ファイルが保存されるフォルダーのパス。
        ///このフォルダー内のファイルの変更を検出してアップロードを行います。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageSourceTranslateFileDirExplanationText {
            get {
                return ResourceManager.GetString("SettingsPageSourceTranslateFileDirExplanationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   翻訳ファイルをmizファイルに適用するユーザーミッションフォルダーのパス。
        ///%userprofile%/Saved Games/DCS/Missions と同じフォルダー構成にしてください。
        ///DCS.openbeta の可能性もあるため注意してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageSourceUserMissionDirExplanationText {
            get {
                return ResourceManager.GetString("SettingsPageSourceUserMissionDirExplanationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーフォルダー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageSourceUserMissionDirText {
            get {
                return ResourceManager.GetString("SettingsPageSourceUserMissionDirText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   翻訳ファイルダウンロードフォルダー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageTranslateFileDirText {
            get {
                return ResourceManager.GetString("SettingsPageTranslateFileDirText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バージョン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageVersionDescriptionTitle {
            get {
                return ResourceManager.GetString("SettingsPageVersionDescriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プライバシーポリシー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPrivacyPolicyTitle {
            get {
                return ResourceManager.GetString("SettingsPrivacyPolicyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   戻る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShellGoBackButton {
            get {
                return ResourceManager.GetString("ShellGoBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PRを作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UploadPageCreatePRButtonContentText {
            get {
                return ResourceManager.GetString("UploadPageCreatePRButtonContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UploadPageFetchButtonContentText {
            get {
                return ResourceManager.GetString("UploadPageFetchButtonContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UploadPageFilterAllContentText {
            get {
                return ResourceManager.GetString("UploadPageFilterAllContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UploadPageFilterLocalOnlyText {
            get {
                return ResourceManager.GetString("UploadPageFilterLocalOnlyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変更/更新 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UploadPageFilterModifiedText {
            get {
                return ResourceManager.GetString("UploadPageFilterModifiedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未DL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UploadPageFilterRepoOnlyText {
            get {
                return ResourceManager.GetString("UploadPageFilterRepoOnlyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DL済 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UploadPageFilterUnchangedText {
            get {
                return ResourceManager.GetString("UploadPageFilterUnchangedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォルダ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UploadPageOpenDirectoryButtonContent {
            get {
                return ResourceManager.GetString("UploadPageOpenDirectoryButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upload に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UploadPageTitle {
            get {
                return ResourceManager.GetString("UploadPageTitle", resourceCulture);
            }
        }
    }
}
