//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DcsTranslationTool.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings_Translation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_Translation() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DcsTranslationTool.Resources.Strings.Translation", typeof(Strings_Translation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   翻訳を作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationButtonContent {
            get {
                return ResourceManager.GetString("CreateTranslationButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationCloseConfirmationCancelButtonText {
            get {
                return ResourceManager.GetString("CreateTranslationCloseConfirmationCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   閉じる に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationCloseConfirmationConfirmButtonText {
            get {
                return ResourceManager.GetString("CreateTranslationCloseConfirmationConfirmButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   翻訳内容が変更されています。閉じてもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationCloseConfirmationMessage {
            get {
                return ResourceManager.GetString("CreateTranslationCloseConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationCloseConfirmationTitle {
            get {
                return ResourceManager.GetString("CreateTranslationCloseConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コピー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationCopyButtonContent {
            get {
                return ResourceManager.GetString("CreateTranslationCopyButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSV ファイルの書き出しに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationCsvExportFailedMessage {
            get {
                return ResourceManager.GetString("CreateTranslationCsvExportFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSV ファイルを書き出しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationCsvExportingMessage {
            get {
                return ResourceManager.GetString("CreateTranslationCsvExportingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSV ファイルを書き出しました: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationCsvExportSucceededMessage {
            get {
                return ResourceManager.GetString("CreateTranslationCsvExportSucceededMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSV ファイルの読み込みに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationCsvImportFailedMessage {
            get {
                return ResourceManager.GetString("CreateTranslationCsvImportFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSV ファイルを読み込んでいます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationCsvImportingMessage {
            get {
                return ResourceManager.GetString("CreateTranslationCsvImportingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   翻訳テキストが存在します。CSV ファイルの内容で上書きしますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationCsvImportOverwriteConfirmationMessage {
            get {
                return ResourceManager.GetString("CreateTranslationCsvImportOverwriteConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上書き確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationCsvImportOverwriteConfirmationTitle {
            get {
                return ResourceManager.GetString("CreateTranslationCsvImportOverwriteConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSV ファイルの行が現在の dictionary と完全一致しませんでした。一致した (Key, Original) は {0} 件です。一致した行のみ取り込みますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationCsvImportPartialConfirmationMessage {
            get {
                return ResourceManager.GetString("CreateTranslationCsvImportPartialConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   部分取り込み確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationCsvImportPartialConfirmationTitle {
            get {
                return ResourceManager.GetString("CreateTranslationCsvImportPartialConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSV ファイルから {0} 件を取り込みました: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationCsvImportPartialSucceededMessage {
            get {
                return ResourceManager.GetString("CreateTranslationCsvImportPartialSucceededMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSV ファイルを読み込みました: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationCsvImportSucceededMessage {
            get {
                return ResourceManager.GetString("CreateTranslationCsvImportSucceededMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   有効 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationDataGridEnabledHeaderText {
            get {
                return ResourceManager.GetString("CreateTranslationDataGridEnabledHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationDataGridKeyHeaderText {
            get {
                return ResourceManager.GetString("CreateTranslationDataGridKeyHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl+↑ / Ctrl+↓ で項目を移動できます に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationDataGridMoveSelectionShortcutToolTip {
            get {
                return ResourceManager.GetString("CreateTranslationDataGridMoveSelectionShortcutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   原文 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationDataGridOriginalHeaderText {
            get {
                return ResourceManager.GetString("CreateTranslationDataGridOriginalHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   翻訳 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationDataGridTranslatedHeaderText {
            get {
                return ResourceManager.GetString("CreateTranslationDataGridTranslatedHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   右端で折り返す に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationDictionaryDetailsWrapCheckBoxContent {
            get {
                return ResourceManager.GetString("CreateTranslationDictionaryDetailsWrapCheckBoxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   dictionary に項目がありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationDictionaryEmptyMessage {
            get {
                return ResourceManager.GetString("CreateTranslationDictionaryEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   dictionary の書き出しに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationDictionaryExportFailedMessage {
            get {
                return ResourceManager.GetString("CreateTranslationDictionaryExportFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   dictionary を書き出しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationDictionaryExportingMessage {
            get {
                return ResourceManager.GetString("CreateTranslationDictionaryExportingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   dictionary を書き出しました: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationDictionaryExportSucceededMessage {
            get {
                return ResourceManager.GetString("CreateTranslationDictionaryExportSucceededMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   dictionary ファイルの読み込みに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationDictionaryImportFailedMessage {
            get {
                return ResourceManager.GetString("CreateTranslationDictionaryImportFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   dictionary ファイルを読み込んでいます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationDictionaryImportingMessage {
            get {
                return ResourceManager.GetString("CreateTranslationDictionaryImportingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   翻訳テキストが存在します。dictionary ファイルの内容で上書きしますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationDictionaryImportOverwriteConfirmationMessage {
            get {
                return ResourceManager.GetString("CreateTranslationDictionaryImportOverwriteConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上書き確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationDictionaryImportOverwriteConfirmationTitle {
            get {
                return ResourceManager.GetString("CreateTranslationDictionaryImportOverwriteConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読み込んだdictionaryファイルが古くなっています。注意して適用してください。一致した key は {0} 件です。一致した項目のみ取り込みますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationDictionaryImportPartialConfirmationMessage {
            get {
                return ResourceManager.GetString("CreateTranslationDictionaryImportPartialConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   警告 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationDictionaryImportPartialConfirmationTitle {
            get {
                return ResourceManager.GetString("CreateTranslationDictionaryImportPartialConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   dictionary ファイルから {0} 件を取り込みました: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationDictionaryImportPartialSucceededMessage {
            get {
                return ResourceManager.GetString("CreateTranslationDictionaryImportPartialSucceededMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   dictionary ファイルを読み込みました: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationDictionaryImportSucceededMessage {
            get {
                return ResourceManager.GetString("CreateTranslationDictionaryImportSucceededMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   dictionary の読み込みに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationDictionaryLoadFailedMessage {
            get {
                return ResourceManager.GetString("CreateTranslationDictionaryLoadFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   dictionary を読み込んでいます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationDictionaryLoadingMessage {
            get {
                return ResourceManager.GetString("CreateTranslationDictionaryLoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   警告 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationEmbeddedJapaneseDictionaryConfirmationTitle {
            get {
                return ResourceManager.GetString("CreateTranslationEmbeddedJapaneseDictionaryConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この dictionary を翻訳の初期値として取り込みますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationEmbeddedJapaneseDictionaryImportConfirmationMessage {
            get {
                return ResourceManager.GetString("CreateTranslationEmbeddedJapaneseDictionaryImportConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取り込み確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationEmbeddedJapaneseDictionaryImportConfirmationTitle {
            get {
                return ResourceManager.GetString("CreateTranslationEmbeddedJapaneseDictionaryImportConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} ファイルには既に日本語のdictionaryファイルが含まれています。継続しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationEmbeddedJapaneseDictionaryMizConfirmationMessage {
            get {
                return ResourceManager.GetString("CreateTranslationEmbeddedJapaneseDictionaryMizConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} ファイルには既に日本語のdictionaryファイルが含まれています。継続しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationEmbeddedJapaneseDictionaryTrkConfirmationMessage {
            get {
                return ResourceManager.GetString("CreateTranslationEmbeddedJapaneseDictionaryTrkConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   書き出し に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationExportButtonContent {
            get {
                return ResourceManager.GetString("CreateTranslationExportButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSVに書き出し に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationExportCsvButtonContent {
            get {
                return ResourceManager.GetString("CreateTranslationExportCsvButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   poファイルに書き出し に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationExportPoButtonContent {
            get {
                return ResourceManager.GetString("CreateTranslationExportPoButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   POに書き出し に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationExportPoSplitButtonContent {
            get {
                return ResourceManager.GetString("CreateTranslationExportPoSplitButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   空欄を非表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationHideEmptyOriginalFilterText {
            get {
                return ResourceManager.GetString("CreateTranslationHideEmptyOriginalFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   原文が空の文字列である項目を非表示にします に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationHideEmptyOriginalFilterToolTip {
            get {
                return ResourceManager.GetString("CreateTranslationHideEmptyOriginalFilterToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象外を非表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationHidePossibleNonTranslationTargetsFilterText {
            get {
                return ResourceManager.GetString("CreateTranslationHidePossibleNonTranslationTargetsFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   翻訳対象外であると思われる以下の項目を非表示にします
        ///- キーが DictKey_ から始まらない
        ///- キーが DictKey_WptName_* に当てはまる
        ///- キーが DictKey_ActionComment_* に当てはまる
        ///- キーが DictKey_GroupName_* に当てはまる
        ///- キーが DictKey_UnitName_* に当てはまる
        ///- 原文がluaコードとして解釈できる に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationHidePossibleNonTranslationTargetsFilterToolTip {
            get {
                return ResourceManager.GetString("CreateTranslationHidePossibleNonTranslationTargetsFilterToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSVから読み込み に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationImportCsvButtonContent {
            get {
                return ResourceManager.GetString("CreateTranslationImportCsvButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   dictionaryから読み込み に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationImportDictionaryButtonContent {
            get {
                return ResourceManager.GetString("CreateTranslationImportDictionaryButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   poファイルから読み込み に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationImportPoButtonContent {
            get {
                return ResourceManager.GetString("CreateTranslationImportPoButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   POから読み込み に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationImportPoSplitButtonContent {
            get {
                return ResourceManager.GetString("CreateTranslationImportPoSplitButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   原文をコピーしました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationOriginalCopiedMessage {
            get {
                return ResourceManager.GetString("CreateTranslationOriginalCopiedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   原文 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationOriginalLabelText {
            get {
                return ResourceManager.GetString("CreateTranslationOriginalLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PO ファイルの書き出しに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationPoExportFailedMessage {
            get {
                return ResourceManager.GetString("CreateTranslationPoExportFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PO ファイルを書き出しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationPoExportingMessage {
            get {
                return ResourceManager.GetString("CreateTranslationPoExportingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PO ファイルを書き出しました: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationPoExportSucceededMessage {
            get {
                return ResourceManager.GetString("CreateTranslationPoExportSucceededMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PO ファイルの読み込みに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationPoImportFailedMessage {
            get {
                return ResourceManager.GetString("CreateTranslationPoImportFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PO ファイルを読み込んでいます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationPoImportingMessage {
            get {
                return ResourceManager.GetString("CreateTranslationPoImportingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   翻訳テキストが存在します。PO ファイルの内容で上書きしますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationPoImportOverwriteConfirmationMessage {
            get {
                return ResourceManager.GetString("CreateTranslationPoImportOverwriteConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上書き確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationPoImportOverwriteConfirmationTitle {
            get {
                return ResourceManager.GetString("CreateTranslationPoImportOverwriteConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PO ファイルのエントリーが現在の dictionary と完全一致しませんでした。一致した (msgctxt, msgid) は {0} 件です。一致したエントリーのみ取り込みますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationPoImportPartialConfirmationMessage {
            get {
                return ResourceManager.GetString("CreateTranslationPoImportPartialConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   部分取り込み確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationPoImportPartialConfirmationTitle {
            get {
                return ResourceManager.GetString("CreateTranslationPoImportPartialConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PO ファイルから {0} 件を取り込みました: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationPoImportPartialSucceededMessage {
            get {
                return ResourceManager.GetString("CreateTranslationPoImportPartialSucceededMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PO ファイルを読み込みました: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationPoImportSucceededMessage {
            get {
                return ResourceManager.GetString("CreateTranslationPoImportSucceededMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無効状態の項目を表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationShowDisabledItemsFilterText {
            get {
                return ResourceManager.GetString("CreateTranslationShowDisabledItemsFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   有効状態の項目を表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationShowEnabledItemsFilterText {
            get {
                return ResourceManager.GetString("CreateTranslationShowEnabledItemsFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未翻訳のみ表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationShowOnlyUntranslatedFilterText {
            get {
                return ResourceManager.GetString("CreateTranslationShowOnlyUntranslatedFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Translated に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationTranslatedLabelText {
            get {
                return ResourceManager.GetString("CreateTranslationTranslatedLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   翻訳作成ウィンドウを開けませんでした に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationWindowOpenFailedMessage {
            get {
                return ResourceManager.GetString("CreateTranslationWindowOpenFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   翻訳を作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationWindowTitle {
            get {
                return ResourceManager.GetString("CreateTranslationWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このカテゴリに翻訳対象アーカイブはありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EmptyMessage {
            get {
                return ResourceManager.GetString("EmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   翻訳対象アーカイブの読み込みに失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoadFailedMessage {
            get {
                return ResourceManager.GetString("LoadFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォルダーを開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenDirectoryButtonContent {
            get {
                return ResourceManager.GetString("OpenDirectoryButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォルダーを開けませんでした に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenDirectoryFailedMessage {
            get {
                return ResourceManager.GetString("OpenDirectoryFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再読み込み に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RefreshButtonContent {
            get {
                return ResourceManager.GetString("RefreshButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DCS World または User Missions の探索元フォルダーを設定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsNotConfiguredMessage {
            get {
                return ResourceManager.GetString("SettingsNotConfiguredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   翻訳 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
