//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DcsTranslationTool.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings_Download {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_Download() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DcsTranslationTool.Resources.Strings.Download", typeof(Strings_Download).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   適用 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApplyButtonContent {
            get {
                return ResourceManager.GetString("ApplyButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DownloadButtonContent {
            get {
                return ResourceManager.GetString("DownloadButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FetchButtonContent {
            get {
                return ResourceManager.GetString("FetchButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FilterAllContentText {
            get {
                return ResourceManager.GetString("FilterAllContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FilterLocalOnlyText {
            get {
                return ResourceManager.GetString("FilterLocalOnlyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変更/更新 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FilterModifiedText {
            get {
                return ResourceManager.GetString("FilterModifiedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未DL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FilterRepoOnlyText {
            get {
                return ResourceManager.GetString("FilterRepoOnlyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DL済 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FilterUnchangedText {
            get {
                return ResourceManager.GetString("FilterUnchangedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全てローカル版を適用 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModifiedApplyModeDialogApplyAllLocalButtonText {
            get {
                return ResourceManager.GetString("ModifiedApplyModeDialogApplyAllLocalButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全てサーバー版を適用 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModifiedApplyModeDialogApplyAllRepositoryButtonText {
            get {
                return ResourceManager.GetString("ModifiedApplyModeDialogApplyAllRepositoryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   中止 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModifiedApplyModeDialogCancelButtonText {
            get {
                return ResourceManager.GetString("ModifiedApplyModeDialogCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   差分があるファイルが {0} 件含まれます。適用方法を選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModifiedApplyModeDialogMessage {
            get {
                return ResourceManager.GetString("ModifiedApplyModeDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   個別に選択する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModifiedApplyModeDialogSelectIndividuallyButtonText {
            get {
                return ResourceManager.GetString("ModifiedApplyModeDialogSelectIndividuallyButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   差分ファイルの適用方法 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModifiedApplyModeDialogTitle {
            get {
                return ResourceManager.GetString("ModifiedApplyModeDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   中止 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModifiedApplySelectionDialogCancelButtonText {
            get {
                return ResourceManager.GetString("ModifiedApplySelectionDialogCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   決定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModifiedApplySelectionDialogConfirmButtonText {
            get {
                return ResourceManager.GetString("ModifiedApplySelectionDialogConfirmButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ローカル版 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModifiedApplySelectionDialogLocalHeader {
            get {
                return ResourceManager.GetString("ModifiedApplySelectionDialogLocalHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   差分ファイルごとに適用元を選択してください。初期値は全てローカル版です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModifiedApplySelectionDialogMessage {
            get {
                return ResourceManager.GetString("ModifiedApplySelectionDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModifiedApplySelectionDialogPathHeader {
            get {
                return ResourceManager.GetString("ModifiedApplySelectionDialogPathHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバー版 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModifiedApplySelectionDialogRepositoryHeader {
            get {
                return ResourceManager.GetString("ModifiedApplySelectionDialogRepositoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   差分ファイルの個別選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModifiedApplySelectionDialogTitle {
            get {
                return ResourceManager.GetString("ModifiedApplySelectionDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォルダ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenDirectoryButtonContent {
            get {
                return ResourceManager.GetString("OpenDirectoryButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
