//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DcsTranslationTool.Resources {
    using System;


    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings_Settings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_Settings() {
        }

        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DcsTranslationTool.Resources.Strings.Settings", typeof(Strings_Settings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   DCS:World の日本語化をサポートする非公式ツールです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }

        /// <summary>
        ///   このアプリケーションについて に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   フォルダー設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DirectorySettingsTitle {
            get {
                return ResourceManager.GetString("DirectorySettingsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   プライバシーポリシー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrivacyPolicyText {
            get {
                return ResourceManager.GetString("PrivacyPolicyText", resourceCulture);
            }
        }

        /// <summary>
        ///   プライバシーポリシー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrivacyPolicyTitle {
            get {
                return ResourceManager.GetString("PrivacyPolicyTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   最新版を探す に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReleaseLatestText {
            get {
                return ResourceManager.GetString("ReleaseLatestText", resourceCulture);
            }
        }

        /// <summary>
        ///   参照 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectButton {
            get {
                return ResourceManager.GetString("SelectButton", resourceCulture);
            }
        }

        /// <summary>
        ///   翻訳ファイルをmiz/trkファイルに適用する機体フォルダーのパス。
        ///&lt;DCSWorldインストールディレクトリ&gt;/Mods/aircraft と同じフォルダー構成にしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SourceAircraftDirExplanationText {
            get {
                return ResourceManager.GetString("SourceAircraftDirExplanationText", resourceCulture);
            }
        }

        /// <summary>
        ///   Aircraft フォルダー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SourceAircraftDirText {
            get {
                return ResourceManager.GetString("SourceAircraftDirText", resourceCulture);
            }
        }

        /// <summary>
        ///   翻訳ファイルをmiz/trkファイルに適用するDLCキャンペーンフォルダーのパス。
        ///&lt;DCSWorldインストールディレクトリ&gt;/Mods/campaigns と同じフォルダー構成にしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SourceDlcCampaignDirExplanationText {
            get {
                return ResourceManager.GetString("SourceDlcCampaignDirExplanationText", resourceCulture);
            }
        }

        /// <summary>
        ///   Campaigns フォルダー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SourceDlcCampaignDirText {
            get {
                return ResourceManager.GetString("SourceDlcCampaignDirText", resourceCulture);
            }
        }

        /// <summary>
        ///   ダウンロードした翻訳ファイルが保存されるフォルダーのパス。
        ///このフォルダー内のファイルの変更を検出してアップロードを行います。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SourceTranslateFileDirExplanationText {
            get {
                return ResourceManager.GetString("SourceTranslateFileDirExplanationText", resourceCulture);
            }
        }

        /// <summary>
        ///   翻訳ファイルをmiz/trkファイルに適用するユーザーミッションフォルダーのパス。
        ///%userprofile%/Saved Games/DCS/Missions と同じフォルダー構成にしてください。
        ///DCS.openbeta の可能性もあるため注意してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SourceUserMissionDirExplanationText {
            get {
                return ResourceManager.GetString("SourceUserMissionDirExplanationText", resourceCulture);
            }
        }

        /// <summary>
        ///   ユーザーフォルダー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SourceUserMissionDirText {
            get {
                return ResourceManager.GetString("SourceUserMissionDirText", resourceCulture);
            }
        }

        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }

        /// <summary>
        ///   翻訳ファイルダウンロードフォルダー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TranslateFileDirText {
            get {
                return ResourceManager.GetString("TranslateFileDirText", resourceCulture);
            }
        }

        /// <summary>
        ///   バージョン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VersionDescriptionTitle {
            get {
                return ResourceManager.GetString("VersionDescriptionTitle", resourceCulture);
            }
        }
    }
}
