//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DcsTranslationTool.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings_Translation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_Translation() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DcsTranslationTool.Resources.Strings.Translation", typeof(Strings_Translation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   翻訳を作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationButtonContent {
            get {
                return ResourceManager.GetString("CreateTranslationButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   dictionary に項目がありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationDictionaryEmptyMessage {
            get {
                return ResourceManager.GetString("CreateTranslationDictionaryEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   dictionary の読み込みに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationDictionaryLoadFailedMessage {
            get {
                return ResourceManager.GetString("CreateTranslationDictionaryLoadFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   dictionary を読み込んでいます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationDictionaryLoadingMessage {
            get {
                return ResourceManager.GetString("CreateTranslationDictionaryLoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   空欄を非表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationHideEmptyOriginalFilterText {
            get {
                return ResourceManager.GetString("CreateTranslationHideEmptyOriginalFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象外を非表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationHidePossibleNonTranslationTargetsFilterText {
            get {
                return ResourceManager.GetString("CreateTranslationHidePossibleNonTranslationTargetsFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Original に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationOriginalLabelText {
            get {
                return ResourceManager.GetString("CreateTranslationOriginalLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未翻訳のみ表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationShowOnlyUntranslatedFilterText {
            get {
                return ResourceManager.GetString("CreateTranslationShowOnlyUntranslatedFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Translated に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationTranslatedLabelText {
            get {
                return ResourceManager.GetString("CreateTranslationTranslatedLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   翻訳作成ウィンドウを開けませんでした に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationWindowOpenFailedMessage {
            get {
                return ResourceManager.GetString("CreateTranslationWindowOpenFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   翻訳を作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateTranslationWindowTitle {
            get {
                return ResourceManager.GetString("CreateTranslationWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このカテゴリに翻訳対象アーカイブはありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EmptyMessage {
            get {
                return ResourceManager.GetString("EmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   翻訳対象アーカイブの読み込みに失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoadFailedMessage {
            get {
                return ResourceManager.GetString("LoadFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォルダーを開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenDirectoryButtonContent {
            get {
                return ResourceManager.GetString("OpenDirectoryButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォルダーを開けませんでした に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenDirectoryFailedMessage {
            get {
                return ResourceManager.GetString("OpenDirectoryFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再読み込み に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RefreshButtonContent {
            get {
                return ResourceManager.GetString("RefreshButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DCS World または User Missions の探索元フォルダーを設定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsNotConfiguredMessage {
            get {
                return ResourceManager.GetString("SettingsNotConfiguredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   翻訳 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
