//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DcsTranslationTool.Resources {
    using System;


    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings_CreatePullRequest {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_CreatePullRequest() {
        }

        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DcsTranslationTool.Resources.Strings.CreatePullRequest", typeof(Strings_CreatePullRequest).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   確認事項 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmationLabel {
            get {
                return ResourceManager.GetString("ConfirmationLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   PRを作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreatePRButtonContent {
            get {
                return ResourceManager.GetString("CreatePRButtonContent", resourceCulture);
            }
        }

        /// <summary>
        ///   削除するファイルリスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteFileListHeader {
            get {
                return ResourceManager.GetString("DeleteFileListHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   &lt;!-- 具体的な変更内容を記載してください --&gt;
        ///- miz/trkファイル単位で箇条書きで記載してください
        ///- 機体やキャンペーン全体に関連する場合、機体やキャンペーンごとの記載でも大丈夫です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogPullRequestDetailPlaceholder {
            get {
                return ResourceManager.GetString("DialogPullRequestDetailPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   &lt;!-- このPRを使用するうえで注意すべきことをリストアップしてください --&gt;
        ///&lt;!-- 必要がなければ N/A としてください --&gt;
        ///N/A に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogPullRequestNotePlaceholder {
            get {
                return ResourceManager.GetString("DialogPullRequestNotePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   主な変更点 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainChangesLabel {
            get {
                return ResourceManager.GetString("MainChangesLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   PRタイトル： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PRTitleLabel {
            get {
                return ResourceManager.GetString("PRTitleLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   変更内容 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PullRequestDetailTitle {
            get {
                return ResourceManager.GetString("PullRequestDetailTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   留意点 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PullRequestNoteTitle {
            get {
                return ResourceManager.GetString("PullRequestNoteTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   この変更の目的・背景を簡潔に書いてください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PullRequestSummaryPlaceholder {
            get {
                return ResourceManager.GetString("PullRequestSummaryPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   概要 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PullRequestSummaryTitle {
            get {
                return ResourceManager.GetString("PullRequestSummaryTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   アップロードするファイルリスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UploadFileListHeader {
            get {
                return ResourceManager.GetString("UploadFileListHeader", resourceCulture);
            }
        }
    }
}
