// <auto-generated/>
#pragma warning disable CS0618
using DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr;
using DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths;
using DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFiles;
using DcsTranslationTool.Infrastructure.Http.ApiClient.Health;
using DcsTranslationTool.Infrastructure.Http.ApiClient.Tree;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace DcsTranslationTool.Infrastructure.Http.ApiClient
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiClient : BaseRequestBuilder
    {
        /// <summary>The createPr property</summary>
        public global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrRequestBuilder CreatePr
        {
            get => new global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The downloadFilePaths property</summary>
        public global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePathsRequestBuilder DownloadFilePaths
        {
            get => new global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFilePaths.DownloadFilePathsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The downloadFiles property</summary>
        public global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFiles.DownloadFilesRequestBuilder DownloadFiles
        {
            get => new global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadFiles.DownloadFilesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The health property</summary>
        public global::DcsTranslationTool.Infrastructure.Http.ApiClient.Health.HealthRequestBuilder Health
        {
            get => new global::DcsTranslationTool.Infrastructure.Http.ApiClient.Health.HealthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tree property</summary>
        public global::DcsTranslationTool.Infrastructure.Http.ApiClient.Tree.TreeRequestBuilder Tree
        {
            get => new global::DcsTranslationTool.Infrastructure.Http.ApiClient.Tree.TreeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.ApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
            if (string.IsNullOrEmpty(RequestAdapter.BaseUrl))
            {
                RequestAdapter.BaseUrl = "https://dcs-translation-japanese-cloudflare-worker.dcs-translation-japanese.workers.dev";
            }
            PathParameters.TryAdd("baseurl", RequestAdapter.BaseUrl);
        }
    }
}
#pragma warning restore CS0618
