// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr
{
    /// <summary>
    /// Builds and executes requests for operations under \create-pr
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CreatePrRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CreatePrRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/create-pr", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CreatePrRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/create-pr", rawUrl)
        {
        }
        /// <summary>
        /// 指定のブランチにファイル変更をコミットし、Pull Request を作成します。リクエスト:- prTitle: PR のタイトル（必須）- prBody: PR の本文（任意）- branchName: 作成または更新するブランチ名（必須）- commitMessage: コミットメッセージ（任意、未指定時はデフォルト）- files: 変更対象の配列。{ path, content, operation }。operation は upsert|delete。検証/安全性:- path は ensureUserPathSafe によってパス走査などを防止します。応答:- 成功時は prNumber, prUrl, branchName, commitSha, note を含む配列を返します。エラー:- 400: リクエスト不正- 403: 権限不足- 422: 処理不能（内容不整合など）- 500: サーバエラー
        /// </summary>
        /// <returns>A <see cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePr400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePr403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePr422Error">When receiving a 422 status code</exception>
        /// <exception cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePr500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrPostResponse?> PostAsCreatePrPostResponseAsync(global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrPostResponse> PostAsCreatePrPostResponseAsync(global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePr400Error.CreateFromDiscriminatorValue },
                { "403", global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePr403Error.CreateFromDiscriminatorValue },
                { "422", global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePr422Error.CreateFromDiscriminatorValue },
                { "500", global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePr500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrPostResponse>(requestInfo, global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 指定のブランチにファイル変更をコミットし、Pull Request を作成します。リクエスト:- prTitle: PR のタイトル（必須）- prBody: PR の本文（任意）- branchName: 作成または更新するブランチ名（必須）- commitMessage: コミットメッセージ（任意、未指定時はデフォルト）- files: 変更対象の配列。{ path, content, operation }。operation は upsert|delete。検証/安全性:- path は ensureUserPathSafe によってパス走査などを防止します。応答:- 成功時は prNumber, prUrl, branchName, commitSha, note を含む配列を返します。エラー:- 400: リクエスト不正- 403: 権限不足- 422: 処理不能（内容不整合など）- 500: サーバエラー
        /// </summary>
        /// <returns>A <see cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePr400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePr403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePr422Error">When receiving a 422 status code</exception>
        /// <exception cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePr500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use PostAsCreatePrPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrResponse?> PostAsync(global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrResponse> PostAsync(global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePr400Error.CreateFromDiscriminatorValue },
                { "403", global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePr403Error.CreateFromDiscriminatorValue },
                { "422", global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePr422Error.CreateFromDiscriminatorValue },
                { "500", global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePr500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrResponse>(requestInfo, global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 指定のブランチにファイル変更をコミットし、Pull Request を作成します。リクエスト:- prTitle: PR のタイトル（必須）- prBody: PR の本文（任意）- branchName: 作成または更新するブランチ名（必須）- commitMessage: コミットメッセージ（任意、未指定時はデフォルト）- files: 変更対象の配列。{ path, content, operation }。operation は upsert|delete。検証/安全性:- path は ensureUserPathSafe によってパス走査などを防止します。応答:- 成功時は prNumber, prUrl, branchName, commitSha, note を含む配列を返します。エラー:- 400: リクエスト不正- 403: 権限不足- 422: 処理不能（内容不整合など）- 500: サーバエラー
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrRequestBuilder WithUrl(string rawUrl)
        {
            return new global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CreatePrRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
