// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CreatePrPostRequestBody_filesMember1_operation
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "upsert")]
        #pragma warning disable CS1591
        Upsert,
        #pragma warning restore CS1591
    }
}
