// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreatePrPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The branchName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BranchName { get; set; }
#nullable restore
#else
        public string BranchName { get; set; }
#endif
        /// <summary>The commitMessage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CommitMessage { get; set; }
#nullable restore
#else
        public string CommitMessage { get; set; }
#endif
        /// <summary>The files property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrPostRequestBody.CreatePrPostRequestBody_files>? Files { get; set; }
#nullable restore
#else
        public List<global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrPostRequestBody.CreatePrPostRequestBody_files> Files { get; set; }
#endif
        /// <summary>The prBody property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PrBody { get; set; }
#nullable restore
#else
        public string PrBody { get; set; }
#endif
        /// <summary>The prTitle property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PrTitle { get; set; }
#nullable restore
#else
        public string PrTitle { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrPostRequestBody"/> and sets the default values.
        /// </summary>
        public CreatePrPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "branchName", n => { BranchName = n.GetStringValue(); } },
                { "commitMessage", n => { CommitMessage = n.GetStringValue(); } },
                { "files", n => { Files = n.GetCollectionOfObjectValues<global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrPostRequestBody.CreatePrPostRequestBody_files>(global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrPostRequestBody.CreatePrPostRequestBody_files.CreateFromDiscriminatorValue)?.AsList(); } },
                { "prBody", n => { PrBody = n.GetStringValue(); } },
                { "prTitle", n => { PrTitle = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("branchName", BranchName);
            writer.WriteStringValue("commitMessage", CommitMessage);
            writer.WriteCollectionOfObjectValues<global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrPostRequestBody.CreatePrPostRequestBody_files>("files", Files);
            writer.WriteStringValue("prBody", PrBody);
            writer.WriteStringValue("prTitle", PrTitle);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrPostRequestBody_filesMember1"/>, <see cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrPostRequestBody_filesMember2"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CreatePrPostRequestBody_files : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrPostRequestBody_filesMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrPostRequestBody_filesMember1? CreatePrPostRequestBodyFilesMember1 { get; set; }
#nullable restore
#else
            public global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrPostRequestBody_filesMember1 CreatePrPostRequestBodyFilesMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrPostRequestBody_filesMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrPostRequestBody_filesMember2? CreatePrPostRequestBodyFilesMember2 { get; set; }
#nullable restore
#else
            public global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrPostRequestBody_filesMember2 CreatePrPostRequestBodyFilesMember2 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrPostRequestBody.CreatePrPostRequestBody_files"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrPostRequestBody.CreatePrPostRequestBody_files CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrPostRequestBody.CreatePrPostRequestBody_files();
                result.CreatePrPostRequestBodyFilesMember1 = new global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrPostRequestBody_filesMember1();
                result.CreatePrPostRequestBodyFilesMember2 = new global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrPostRequestBody_filesMember2();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CreatePrPostRequestBodyFilesMember1 != null || CreatePrPostRequestBodyFilesMember2 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(CreatePrPostRequestBodyFilesMember1, CreatePrPostRequestBodyFilesMember2);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                writer.WriteObjectValue<global::DcsTranslationTool.Infrastructure.Http.ApiClient.CreatePr.CreatePrPostRequestBody_filesMember1>(null, CreatePrPostRequestBodyFilesMember1, CreatePrPostRequestBodyFilesMember2);
            }
        }
    }
}
#pragma warning restore CS0618
