// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadZip
{
    /// <summary>
    /// Builds and executes requests for operations under \download-zip
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DownloadZipRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadZip.DownloadZipRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DownloadZipRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/download-zip", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadZip.DownloadZipRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DownloadZipRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/download-zip", rawUrl)
        {
        }
        /// <returns>A <see cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadZip.DownloadZipPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadZip.DownloadZip400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadZip.DownloadZip403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadZip.DownloadZip404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadZip.DownloadZip422Error">When receiving a 422 status code</exception>
        /// <exception cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadZip.DownloadZip500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadZip.DownloadZipPostResponse?> PostAsDownloadZipPostResponseAsync(global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadZip.DownloadZipPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadZip.DownloadZipPostResponse> PostAsDownloadZipPostResponseAsync(global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadZip.DownloadZipPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadZip.DownloadZip400Error.CreateFromDiscriminatorValue },
                { "403", global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadZip.DownloadZip403Error.CreateFromDiscriminatorValue },
                { "404", global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadZip.DownloadZip404Error.CreateFromDiscriminatorValue },
                { "422", global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadZip.DownloadZip422Error.CreateFromDiscriminatorValue },
                { "500", global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadZip.DownloadZip500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadZip.DownloadZipPostResponse>(requestInfo, global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadZip.DownloadZipPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadZip.DownloadZipResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadZip.DownloadZip400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadZip.DownloadZip403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadZip.DownloadZip404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadZip.DownloadZip422Error">When receiving a 422 status code</exception>
        /// <exception cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadZip.DownloadZip500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use PostAsDownloadZipPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadZip.DownloadZipResponse?> PostAsync(global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadZip.DownloadZipPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadZip.DownloadZipResponse> PostAsync(global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadZip.DownloadZipPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadZip.DownloadZip400Error.CreateFromDiscriminatorValue },
                { "403", global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadZip.DownloadZip403Error.CreateFromDiscriminatorValue },
                { "404", global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadZip.DownloadZip404Error.CreateFromDiscriminatorValue },
                { "422", global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadZip.DownloadZip422Error.CreateFromDiscriminatorValue },
                { "500", global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadZip.DownloadZip500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadZip.DownloadZipResponse>(requestInfo, global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadZip.DownloadZipResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadZip.DownloadZipPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadZip.DownloadZipPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadZip.DownloadZipRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadZip.DownloadZipRequestBuilder WithUrl(string rawUrl)
        {
            return new global::DcsTranslationTool.Infrastructure.Http.ApiClient.DownloadZip.DownloadZipRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DownloadZipRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
