// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace DcsTranslationTool.Infrastructure.Http.ApiClient.Tree
{
    /// <summary>
    /// Builds and executes requests for operations under \tree
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TreeRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.Tree.TreeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TreeRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tree", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.Tree.TreeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TreeRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tree", rawUrl)
        {
        }
        /// <summary>
        /// 指定された GitHub リポジトリのデフォルトブランチから、DCSWorld, UserMissions 配下のファイル一覧（TreeItem配列）を取得して返す。
        /// </summary>
        /// <returns>A <see cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.Tree.TreeGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.Tree.Tree400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.Tree.Tree403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.Tree.Tree422Error">When receiving a 422 status code</exception>
        /// <exception cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.Tree.Tree500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::DcsTranslationTool.Infrastructure.Http.ApiClient.Tree.TreeGetResponse?> GetAsTreeGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::DcsTranslationTool.Infrastructure.Http.ApiClient.Tree.TreeGetResponse> GetAsTreeGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::DcsTranslationTool.Infrastructure.Http.ApiClient.Tree.Tree400Error.CreateFromDiscriminatorValue },
                { "403", global::DcsTranslationTool.Infrastructure.Http.ApiClient.Tree.Tree403Error.CreateFromDiscriminatorValue },
                { "422", global::DcsTranslationTool.Infrastructure.Http.ApiClient.Tree.Tree422Error.CreateFromDiscriminatorValue },
                { "500", global::DcsTranslationTool.Infrastructure.Http.ApiClient.Tree.Tree500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::DcsTranslationTool.Infrastructure.Http.ApiClient.Tree.TreeGetResponse>(requestInfo, global::DcsTranslationTool.Infrastructure.Http.ApiClient.Tree.TreeGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 指定された GitHub リポジトリのデフォルトブランチから、DCSWorld, UserMissions 配下のファイル一覧（TreeItem配列）を取得して返す。
        /// </summary>
        /// <returns>A <see cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.Tree.TreeResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.Tree.Tree400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.Tree.Tree403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.Tree.Tree422Error">When receiving a 422 status code</exception>
        /// <exception cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.Tree.Tree500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsTreeGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::DcsTranslationTool.Infrastructure.Http.ApiClient.Tree.TreeResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::DcsTranslationTool.Infrastructure.Http.ApiClient.Tree.TreeResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::DcsTranslationTool.Infrastructure.Http.ApiClient.Tree.Tree400Error.CreateFromDiscriminatorValue },
                { "403", global::DcsTranslationTool.Infrastructure.Http.ApiClient.Tree.Tree403Error.CreateFromDiscriminatorValue },
                { "422", global::DcsTranslationTool.Infrastructure.Http.ApiClient.Tree.Tree422Error.CreateFromDiscriminatorValue },
                { "500", global::DcsTranslationTool.Infrastructure.Http.ApiClient.Tree.Tree500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::DcsTranslationTool.Infrastructure.Http.ApiClient.Tree.TreeResponse>(requestInfo, global::DcsTranslationTool.Infrastructure.Http.ApiClient.Tree.TreeResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 指定された GitHub リポジトリのデフォルトブランチから、DCSWorld, UserMissions 配下のファイル一覧（TreeItem配列）を取得して返す。
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::DcsTranslationTool.Infrastructure.Http.ApiClient.Tree.TreeRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::DcsTranslationTool.Infrastructure.Http.ApiClient.Tree.TreeRequestBuilder WithUrl(string rawUrl)
        {
            return new global::DcsTranslationTool.Infrastructure.Http.ApiClient.Tree.TreeRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TreeRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
