// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DcsTranslationTool.Infrastructure.Http.ApiClient.Tree
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum TreeGetResponse_data_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "blob")]
        #pragma warning disable CS1591
        Blob,
        #pragma warning restore CS1591
    }
}
